name: style check
on: [push, pull_request]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          version: latest
          args: --check --config-path=.stylua.toml .
